[formatter.actionlint]
command = "/nix/store/wkyi1777bd7q9d48nmqgw790awr7smh4-actionlint-1.7.4/bin/actionlint"
excludes = []
includes = [".github/workflows/*.yml", ".github/workflows/*.yaml"]
options = []

[formatter.clang-format]
command = "/nix/store/cdfrr9g239zw33b0c59a2rj5w021zpn9-clang-tools-18.1.8/bin/clang-format"
excludes = []
includes = ["*.c", "*.cc", "*.cpp", "*.h", "*.hh", "*.hpp"]
options = ["-i"]

[formatter.cmake-format]
command = "/nix/store/9ijpfiihb5hnwy5s6fag0c196z71ycfb-cmake-format-0.6.13/bin/cmake-format"
excludes = []
includes = ["CMakeLists.txt", "**/CMakeLists.txt", "**/*.cmake", "*.cmake", "CMakeLists.txt"]
options = ["--in-place"]

[formatter.dos2unix]
command = "/nix/store/v5kd0y9k0qszrc8smak49954nca7z32i-dos2unix-7.5.2/bin/dos2unix"
excludes = []
includes = ["*"]
options = ["--keepdate"]

[formatter.keep-sorted]
command = "/nix/store/vc66g0xs6azkkdqgahjb7q34naxja7p1-keep-sorted-0.5.1/bin/keep-sorted"
excludes = []
includes = ["*"]
options = []

[formatter.nixfmt]
command = "/nix/store/k6kyjxxk7gc2a29nbhnz3c1ffm42hs6y-nixfmt-unstable-2024-08-16/bin/nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.prettier]
command = "/nix/store/9hwlvnn35g296w83m1088sf1lng0cv9d-prettier-3.3.3/bin/prettier"
excludes = []
includes = ["*.cjs", "*.css", "*.html", "*.js", "*.json", "*.json5", "*.jsx", "*.md", "*.mdx", "*.mjs", "*.scss", "*.ts", "*.tsx", "*.vue", "*.yaml", "*.yml"]
options = ["--write"]

[formatter.ruff-check]
command = "/nix/store/fr45ms4qa181m5896qp0dvypy6qy1a3h-python3.12-ruff-0.7.4-bin/bin/ruff"
excludes = []
includes = ["*.py", "*.pyi"]
options = ["check", "--fix"]

[formatter.ruff-format]
command = "/nix/store/fr45ms4qa181m5896qp0dvypy6qy1a3h-python3.12-ruff-0.7.4-bin/bin/ruff"
excludes = []
includes = ["*.py", "*.pyi"]
options = ["format"]

[formatter.shellcheck]
command = "/nix/store/dkssi8wkf0yg2x0lpmafi49crmyxraix-shellcheck-0.10.0-bin/bin/shellcheck"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = []

[formatter.shfmt]
command = "/nix/store/h2h7x5kiafxihrshxcmg5ah0q4zwhqbj-shfmt-3.10.0/bin/shfmt"
excludes = []
includes = ["*.sh", "*.bash", "*.envrc", "*.envrc.*"]
options = ["-i", "2", "-s", "-w"]

[formatter.taplo]
command = "/nix/store/gc4rj634xf8bk5m2s44mf1qp3hiyj93k-taplo-0.9.3/bin/taplo"
excludes = []
includes = ["*.toml"]
options = ["format"]

[formatter.typos]
command = "/nix/store/aw4ary3snhfyq0hn2zspx60rmqnyk5h5-typos-1.27.3/bin/typos"
excludes = []
includes = ["*"]
options = ["--write-changes"]

[formatter.yamlfmt]
command = "/nix/store/hbjgdsfqz1hc6y95qadhwgggz40kppfd-yamlfmt-0.14.0/bin/yamlfmt"
excludes = []
includes = ["*.yaml", "*.yml"]
options = []

[global]
excludes = ["*.lock", "*.patch", "package-lock.json", "go.mod", "go.sum", ".gitignore", ".gitmodules", ".hgignore", ".svnignore", "build/**", "result/**", "generated/**", "treefmt.toml", "docs/figures-source/**", "docs/pyproject/**", "docs/source/_static/fonts/**", "docs/source/robots.txt", "docs/source/intersphinx/**", "*.rviz", "setup.cfg", "software/ros_ws/src/**/resource/**", "*.drawio", "*.svg", "*.png", "*.jpg", "*.jpeg", "*.gif", "*.bmp", "*.ico", "*.pdf"]
