[default]

extend-ignore-re = [
  # see
  # https://github.com/crate-ci/typos/blob/master/docs/reference.md
  # for the origin of these two regexes
  # disable lines with trailing commented spellchecker:disable-line
  "(?Rm)^.*(?:#|//|%)\\s*spellchecker:disable-line$",
  # disable blocks between spellchecker:off and spellchecker:on
  "(?s)(?:#|//|%)\\s*spellchecker:off.*?\\n\\s*(?:#|//|%)\\s*spellchecker:on",
]

[type.md]
extend-ignore-re = [
  # ignore align: center (for inserting images)
  "(?Rm)^\\s*:?align:\\s*center$",
]
